const Twit = require('twit');

const fs = require( 'fs' ),
      path = require( 'path' ),
      config = require( path.join( __dirname, 'config.js' ) );


const T = new Twit( config );
let stream = T.stream('statuses/filter', { track: '@HintShard' });
let list = [];
let usedList = [];
let timeToTweet = 300000;
let replyCount = 0;



const hintList = [`A bird box in the shade.`,
`A bird box.`,
`A golden circle on a red circle.`,
`A lonely container.`,
`A pair of earrings.`,
`A parakeet on the left shoulder.`,
`A pillar without a treasure.`,
`A red gate.`,
`A sandpit.`,
`A sandy path to the head of a stone statue.`,
`A statue with scary eyes.`,
`A suspended ceiling.`,
`A swirl pyramid.`,
`A swirling arrow.`,
`A swirling container.`,
`A terrace with two legs.`,
`A treasure of four stone statues.`,
`Armored carpool.`,
`At the bottom of a huge wall painting.`,
`At the bottom of a pillar.`,
`At the bottom of a swirl tile pyramid.`,
`At the foot of a pillar.`,
`Behind a face.`,
`Between four birds.`,
`Between the red and green striped pillars.`,
`Between the red pillars.`,
`Between the twin stars.`,
`Between two stone statues.`,
`By a tall pillar.`,
`By a wind jump board.`,
`Double containers.`,
`Four swirling eyes.`,
`Four whirling eyes.`,
`He's holding a box.`,
`In a storm zone.`,
`In front of a bird chest under four feathers.`,
`In front of a mountain with green and red stripes.`,
`In front of a mountain with red and green stripes.`,
`In front of the double containers.`,
`In the center of the 8th pillar.`,
`Inside a statue storage area.`,
`Near a chair.`,
`Near the six pillars.`,
`On a railway.`,
`On a red circle.`,
`On a sandy path that leads to a stone statue head.`,
`On a sandy path to a statue head.`,
`On a sandy path to a stone statue head.`,
`On the lap of a wall painting.`,
`On the pillar.`,
`On the scary eyes in the "Wild Canyon Track."`,
`On the side of a bird chest under four feathers`,
`On the spiral tile.`,
`On the top of ten fingers.`,
`Orbiting above the face.`,
`Over the head.`,
`Over the tilted pillar.`,
`Red and green stripes.`,
`Stone statue quartet.`,
`Swirling.`,
`The altar with six pillars.`,
`The arrow pointing to the right.`,
`The beginning room.`,
`The golden path.`,
`The head of the 4th stone statue.`,
`The place pointed out by two priests.`,
`Under the elbow.`,
`Under the wings of two birds.`,
`Where the wind blows.`,
`Where wind is generated.`,
`Wild Canyon Track.`,
`A high place.`,
`Dancing rocks.`,
`Down below.`,
`Rolling rocks.`,
`A bright place.`,
`In the valley.`,
`Near a windy place.`,
`By a ring.`,
`On the sand.`,
`In the shade.`,
`A dark place.`,
`In a bright valley.`,
`The windy hall.`,
`A head of a huge statue.`,
`Near a strong wind.`,
`Near the strong wind.`,
`A windy hall.`,
`A shady place.`,
`A Stone landing .`,
`A windy area.`,
`A small place.`,
`Near the ceiling.`,
`In a treasure chest by a red pillar near the lonely statue.`,
`The left treasure chest of three next to each other.`,
`The middle one among three treasure chests next to each other.`,
`The right one among three treasure chests next to each other.`,
`In a treasure chest near an opening you can go down.`,
`On the square building in the upper valley.`,
`Inside a wooden container at the bottom of a red pillar.`,
`By the stone statue face.`,
`On the left shoulder of a lonely stone statue.`,
`The tallest one among the six pillars underground.`,
`In a wooden container by a stone container.`,
`In the treasure chest by the head of a stone statue.`,
`Move around in the armored carpool.`,
`Under the weight that is moving up and down by the wall.`,
`Inside of a statue sealed with a container.`,
`Can you get it if you defeat the GUN's military weapons?`,
`On top of a statue head deep in the valley.`,
`Follow the swirl tiles on the wall.`,
`In a treasure chest under an arrow in a windy hall.`,
`In a wooden container surrounded by swirling panels down below.`,
`Between the two pillars near a area where wind blows.`,
`Under the weight that is moving up and down by a wall.`,
`In a treasure chest up where the wind blows.`,
`A square sandpit, which is blocked by a red pillar.`,
`On the green and red striped stand.`,
`A hidden place in front of a lonely statue.`,
`At the bottom of a tilted pillar near the weight that's moving up and down.`,
`A valley with a lot of square buildings, near the swirl tiles.`,
`A hiding place in front of a lonely statue.`,
`A treasure chest behind a rock that you can push.`,
`At the bottom of a huge swirl arrow.`,
`Between two pillars by a passageway by a wall downstairs.`,
`Under the weight that is moving up and down by the wall`,
`Between two red springs.`,
`Are the stone statues facing each other playing catch?`,
`By the tallest one pillar among six.`,
`Up from where the wind blows.`,
`Two wooden containers next to each other.`,
`Inside of a wooden container under the eye windmill.`,
`Inside a wooden container under the eye windmill.`,
`Under the eye windmill.`,
`On the lap of a lonely stone statue.`,
`The lower area where the wind is generated.`,
`The lower area where wind is generated.`,
`A cliff with two item boxes.`,
`A cliff sticking out under a windmill in the middle of the upper area.`,
`On the cliff sticking out of the middle.`,
`Between two windmills on the head of a stone statue.`,
`Inside a statue sealed in a container.`,
`At the bottom of the statue with one swirl tile.`,
`Try breaking the floating rocks with a Glide attack.`,
`Move a rock with a square face.`,
`On a square building.`,
`Go in between red pillars.`,
`Can you get it if you defeat the GUN's weapons?`,
`Do the GUN weapons have...?`,
`Follow the arrow between two treasure chests.`,
`On the red pillar by the weight that's moving up and down.`,
`On the square building.`,
`Under three swirl tiles near the huge statue head.`,
`On the lap of a sitting statue.`,
`Around a stone statue head.`,
`On the top of the statue's head.`,
`The path to the head of a stone statue, on the tilted pillar.`,
`Two pillars on the cliff with two red springs.`,
`On the three swirling tiles near the head of a stone statue.`,
`The shorter one among six pillars.`,
`Go in between six pillars.`,
`The arrow pointing to the right made of swirling panels.`,
`Between the two pillars where there are three treasure chests.`,
`Between the tall pillars in a hall downstairs.`,
`On a statue that holds four swirl tiles.`,
`In front of a wall painting near an opening that you can go down.`,
`Under the elbow of a statue that is sitting on a chair.`,
`Behind the head of a stone statue.`,
`Circle around a windy area.`,
`In a treasure chest at the bottom of a pillar.`,
`Near an area where the wind is generated upwards.`,
`In front of a twin's head.`,
`In a square statue on a passageway by a wall downstairs.`,
`In a square statue on a passageway by the wall downstairs.`,
`Circle along a path outside the wall.`,
`A farm house.`,
`A missile path.`,
`A path lined with rings.`,
`A place where flames cross.`,
`A place where you can hear the horn.`,
`A place you can hear the horn.`,
`A place you can't jump...`,
`A pumpkin with a creepy smile is looking at...?`,
`A scarecrow protecting a container.`,
`A three-faced ghost?`,
`A three-foot gap.`,
`A tombstone near some grass.`,
`Angel's ring.`,
`Bearded mountain...?`,
`Chimney near some grass.`,
`Cold iron bars...`,
`Endless journey.`,
`Flaming Emeralds.`,
`Flattened grass.`,
`Forgotten hut.`,
`Ghost pumpkin's necklace!`,
`Ghost train station.`,
`Ghost train's guidepost.`,
`In the center of a triangle.`,
`It's a floor and also a ceiling.`,
`It's a floor, but it's also a ceiling?`,
`It's about to fall off.`,
`King of the hill.`,
`Laughing into tears.`,
`Laughing pumpkin.`,
`Lonely tombstone.`,
`Lost pumpkin.`,
`Noise upstairs and downstairs!`,
`On patrol?`,
`On the dangerous material.`,
`Path of the ghost train.`,
`Pray for a good harvest at a holy place.`,
`Pumpkin family.`,
`Pumpkin snowman.`,
`Pumpkin triangle.`,
`Pumpkins who don't get along.`,
`Sad-eyed pumpkin.`,
`Scarecrow's house.`,
`Scramble for the Emeralds!`,
`Second skull from the top, fifth from the bottom.`,
`Shady place.`,
`Skulls on the right and left.`,
`Sleep behind a pumpkin.`,
`Sleep with the dead...`,
`Sleepless house.`,
`Step back from the platform and wait for the next arrival.`,
`Suffering from a stuffed nose?`,
`Tells time...`,
`Terrible! A skull buried in the rocky wall!`,
`The person you are waiting for finally arrived.`,
`The rocket path.`,
`The skull marks the spot.`,
`The tombstone guarded by four skulls.`,
`There is only one on the cliff.`,
`Three against three staring at each other?`,
`Three brothers' tombstone.`,
`Three metal barrels.`,
`Three scarecrow brothers.`,
`Three skull brothers.`,
`Three-faced ghost.`,
`Tombstone by some grass.`,
`Turns but doesn't turn.`,
`Twin huts.`,
`Twin skulls.`,
`Under a chimney.`,
`Under the chimney.`,
`Under the tracks.`,
`Very high up.`,
`Wander around in a circle.`,
`Wander around in a circle...`,
`When you do something bad, this might happen...`,
`You can see it, but you can't take it!`,
`You can see it, but you can't take it...`,
`Pumpkin mountain.`,
`Church mountain.`,
`Ghost train mountain.`,
`Pumpkin field.`,
`Near a mountain with a ghost face.`,
`A mountain with a ghost face.`,
`Passageway leads to the mountains.`,
`In the air.`,
`Under the car that fires a cannon.`,
`Between Church mountain and Pumpkin mountain.`,
`In the ground.`,
`Near Ghost train mountain.`,
`On the tracks.`,
`On Papa's back.`,
`In the rocky wall.`,
`From Pumpkin mountain, you can see...`,
`From Ghost train mountain, you can see...`,
`A ghost face mountain.`,
`Behind a thick rocky wall.`,
`On the top of the mountain.`,
`Near Church mountain.`,
`In the metal barrel on the cliff.`,
`On the rusty steel platform.`,
`Church mountain`,
`A hut on the top of the mountain.`,
`A rocket launch pad at the bottom of the mountain.`,
`Steel beam near the oval tracks.`,
`Between three skull statues on the mountainside.`,
`Under the tracks on the mountainside.`,
`Try placing the ghost train at the bottom using the rotary switch...`,
`Place you can dig but can't jump to, use Y-button to select action window.`,
`Try looking around from the mountain with a creepy smile.`,
`By the foot of a scarecrow on the mountainside.`,
`Above the ghost tree.`,
`Near the foot of stairs on top of the mountain.`,
`Under some grass by a tombstone behind a tunnel.`,
`Circle the mountain with an angry face.`,
`In the middle of some grass growing on the side of a tall mountain.`,
`By the grass roots growing on the chimney near the rotary platform.`,
`A cage between Ghost train mountain and Pumpkin mountain.`,
`The cliff near the foot of the mountain.`,
`The cliff on the mountain with round tracks.`,
`A container on the top of the mountain.`,
`Go around a circle by train.`,
`At the bottom of Pumpkin mountain.`,
`Under the grass of the path of the iron ball.`,
`In a hut on the mountainside.`,
`In the hut on the cliff.`,
`Circle the mountain with a sad face.`,
`Pumpkin station on the mountainside.`,
`Between three ghost trees at the bottom of the mountain.`,
`Under the overhanging steel platform.`,
`Roof of the Church.`,
`Pumpkin altar at the bottom of the mountain.`,
`From Ghost train mountain, glide towards the balloon!`,
`In a car that fires a cannon.`,
`In front of a big Pumpkin on the top of the mountain.`,
`On the top of the mountain shaped like a pumpkin ghost.`,
`In a tombstone on the mountainside.`,
`On Church mountain hillside.`,
`Way down the rotary platform...`,
`Go slowly around the outside of the Pumpkin field.`,
`On the path that leads to Pumpkin mountain.`,
`When you see Pumpkin mountain from where the church bell used be...`,
`Behind the pumpkin on the top of the mountain.`,
`Behind a big pumpkin in a pumpkin field.`,
`Rocky wall by the Pumpkin altar at the foot of the mountain.`,
`Between three pumpkins that you can find using a rocket.`,
`Between pumpkins sitting back to back.`,
`On the mountain shaped like a pumpkin ghost.`,
`The right eye of the mountain shaped like a pumpkin ghost.`,
`Between the trees facing each other .`,
`Between the trees facing each other in the middle of the mountain.`,
`Behind a pumpkin that you can find using a rocket!`,
`Church graveyard.`,
`Behind a tombstone near the passageway in the air.`,
`In the center of the round tracks.`,
`A nose of the mountain shaped like a pumpkin ghost.`,
`Place where the church bell used to be.`,
`Try scaling a mountain from the front without using a rocket!`,
`On the rocket behind the mountain.`,
`Ghost train crosses the rocky wall.`,
`Behind a tombstone on the passageway in the air.`,
`In the metal barrel.`,
`Between the ghost trees facing each other.`,
`Under the tombstone behind a tunnel.`,
`A graveyard at the bottom of Church mountain.`,
`A ghost at the bottom of the mountain is holding...?`,
`Between three scarecrows on the mountainside.`,
`Behind the blazing fire skull statue on the mountainside.`,
`On the path near the bottom of the mountain.`,
`Ghost train's rotating platform.`,
`By the oval tracks.`,
`At the bottom of the mountain.`,
`Near the foot of the only chimney in the pumpkin field.`,
`Rocky wall under the rotary platform.`,
`Rocky wall with oval tracks.`,
`Rocky cliff under the rotary platform.`,
`On the roof of the church.`,
`Try placing the ghost train at the bottom using the rotary switch.`,
`Move the ghost train to the top of the mountain using the rotary switch.`,
`A lonely tombstone at the bottom of the mountain.`,
`Under the tombstone far away.`,
`In a cage at the bottom of the mountain.`,
`In a cage on the mountainside.`,
`A brick room that's always underwater.`,
`A container on the shelf.`,
`A place where the fourth person of the group is buried.`,
`A wooden box on the steel beam.`,
`Above a pair of skulls wearing ties.`,
`Above the skull.`,
`Above the vertical line of skulls.`,
`At the bottom of the main pillar.`,
`At the bottom of the skull fence.`,
`Behind a falling tree.`,
`Behind a square tree.`,
`Behind two heads.`,
`Between the skulls facing each other.`,
`Broken mine cart.`,
`Chase the skull!`,
`Dangerous place.`,
`Dented ceiling.`,
`Dig at the bottom of the slope!`,
`Dig on the slope.`,
`Dig under the triangle skull!`,
`Entrance to the abyss.`,
`Entrance to the mine cart dumping area.`,
`Floating with ghosts.`,
`Ghost path.`,
`Ghost pulley.`,
`Ghost window.`,
`Go back and forth on the tracks.`,
`Guardian of the switch.`,
`How do you make a "X" with skulls?`,
`In an oven.`,
`In front of a family skulls.`,
`In front of a mysterious door.`,
`In front of sign No.2.`,
`In front of the bathing mini-skull.`,
`In the skull fence.`,
`In the triangle skull.`,
`In three metal barrels.`,
`Inside of the overturned mine cart.`,
`It's moving and it's surrounded by blue lights .`,
`Jail window.`,
`Left eye on the jumbo face.`,
`Metal barrel in the luggage area.`,
`Metal barrel where ghosts live.`,
`Mine cart dumping area.`,
`Near the blue flame.`,
`Near the wall.`,
`Next to a skull that seems out of place.`,
`Next to an overturned ghost.`,
`Next to the drain switch.`,
`On the mine cart tracks.`,
`On the steel ghost beam.`,
`On the steel skull beam.`,
`On the tracks of a broken mine cart.`,
`Overturned mine cart.`,
`Passageway to the "Water-Powered Lift."`,
`Path to the abyss.`,
`Red flowers for a skull couple.`,
`Right eye of the jumbo face.`,
`Sealed window.`,
`Skull pair wearing a tie near a metal barrel.`,
`Skull pulley.`,
`Skulls looking at each other in a cave.`,
`Something other than a mine cart?`,
`Stair-shaped brick room.`,
`Switch No.1.5?`,
`Talking skulls near the window.`,
`The container next to the jumbo skull.`,
`The corner of the tracks.`,
`The main pillar.`,
`The skull that is facing the other way.`,
`Three fans.`,
`Three skulls arguing.`,
`Under the blue flame.`,
`Under the flattened ground.`,
`Under the tilted pillar.`,
`Under the triangle skull.`,
`Under the vertical line of skulls.`,
`Underwater brick room.`,
`Water level 2 height.`,
`Wooden window on a roof.`,
`Switch No.3.`,
`Water-Powered Lift hall.`,
`A room behind the "CAUTION" sign that warns about the ghosts.`,
`The "Ghost Room."`,
`The largest room.`,
`High up.`,
`On the narrow path, switch No.2 or No.3.`,
`Switch No.1.`,
`Narrow path, enter from the bottom.`,
`Narrow path, enter from the top.`,
`On the narrow path, switch No.3.`,
`Narrow path.`,
`Underwater.`,
`Switch No.3 on the narrow path.`,
`Under a lot of pillars.`,
`Small place.`,
`Switch No.1 or No.2?`,
`Do you feel a breeze?`,
`Switch No.2 or No.3 on the narrow path.`,
`On a steel platform.`,
`On the narrow path, switch No.1.`,
`A room filled with skulls and ghosts.`,
`A hole behind the "CAUTION" sign that warns about the ghosts.`,
`A container on the pulley in the upper area of the hall.`,
`How do you make a square out skulls that form a triangle?`,
`Try digging into the wooden frame that looks like a window.`,
`Try digging above the top skull.`,
`Center of the bottom of the "Water-Powered Lift" hall.`,
`Near a steel box containing a floating platform at the bottom of the hall.`,
`Next to the lumber in the "Lantern Room."`,
`Try digging next to the lumber in the "Lantern Room."`,
`The corner at the bottom of the "Water-Powered Lift" hall.`,
`Upper area of the narrow path where there is a floating platform.`,
`Inside of the mine cart in the highest room.`,
`Try digging under the moving weight.`,
`Press switch No.2 and jump on the floating platform. Try Spiral Upper!`,
`Very narrow path.`,
`Under the floating platform at the back of the narrow path.`,
`In a mine cart on the narrow path with a floating platform.`,
`Wander behind the "CAUTION" sign that warns about the ghosts.`,
`On the pulley on the wall in the "Water-Powered Lift" hall.`,
`Try digging inside of the wooden window on the roof.`,
`On the tracks in the middle area of the "Water-Powered Lift" hall.`,
`The GUN's machine near the switch in the "Lantern Room."`,
`Try digging between four skulls.`,
`Punch the lid of the oven in the lower area of the hall.`,
`Try digging in front of the skull with a mini-skull at the bottom of the hall.`,
`Try digging in front of the door of the "Lantern Room."`,
`Front of the water level sign in the middle of the"Water-Powered Lift."`,
`Try digging in in front of the first skull you saw in the room.`,
`In the steel box containing a floating platform by the wall in a hall.`,
`Inside the mine cart n the highest room.`,
`The "Lantern Room."`,
`Try digging inside the wooden frame that looks like a window with a fence.`,
`Try digging inside the ring that is over the room with two switches.`,
`In a metal barrel in the corner of the "Water-Powered Lift" hall.`,
`Inside of the mine cart in the highest room .`,
`Narrow path, down below.`,
`Try digging under the blue lantern.`,
`In front of the middle fan.`,
`Try digging to the left of the skull which is the fourth from the top.`,
`Next to a mine cart on the narrow path with tracks.`,
`Next to the switch in the highest room.`,
`Lower area of the narrow path where there is a floating platform`,
`On the skull pillar which supports a cliff by the wall.`,
`The highest room.`,
`On the cliff in the middle area of the "Water-Powered Lift" hall.`,
`Go up and down under the floating platform.`,
`Circle around the spring on the wall.`,
`It's buried under the spring on the wall.`,
`Upper half of the wall of the room with the water level switch.`,
`Try digging inside a wooden frame looking like a window with tilted bars.`,
`In the metal barrels that are next to each other in the hall.`,
`On a turning pulley.`,
`GUN's car with spikes.`,
`Underwater path behind "CAUTION" sign that warns about the ghosts.`,
`Try digging between two switches.`,
`In a wooden box on the narrow path with a floating platform.`,
`Lower area of the narrow path where there is a floating platform.`,
`Go around the pillar in the center of the hall.`,
`Try digging in front of the only skull facing the opposite way among four.`,
`In front of three propellers in the upper area of the hall.`,
`The center of three propellers in the upper area of the hall.`,
`Try digging in the area where the three skulls are looking at...?`,
`Under the light in the highest room.`,
`Upper area of the narrow path with a floating platform.`,
`Try digging in the area under the skulls lined up near the wall.`,
`Ghosts are waiting for you!`,
`On a wooden frame that looks like a window on a wall.`,
`Above the small flame.`,
`Bat's nest.`,
`Between the legs.`,
`Black and yellow stripes.`,
`Bug's defense.`,
`Bug's food.`,
`Burning mad...`,
`Cowering beetle.`,
`E - 01.`,
`Embarrassing place.`,
`Eyes bugged out...?`,
`Fly higher than a bird!`,
`Four square pillars.`,
`Golden goddess.`,
`In the middle of red eyes.`,
`It will appear when you get closer...`,
`Junk storage.`,
`Long vertical white line. `,
`Patterned shorts.`,
`Scorpion tattoo.`,
`Shoe box.`,
`Snakes looking at each other.`,
`Stink Bug...`,
`The bat and the hourglass.`,
`Three container brothers.`,
`Treasure chest storage.`,
`Two mouths.`,
`Water bug. `,
`White dot indicates blue.`,
`Yellow and black stripes.`,
`A bat and a scorpion.`,
`Beauty and the beast.`,
`Bug's baby.`,
`Bugs chatting.`,
`Bugs don't like it.`,
`Corner light.`,
`Four leaves.`,
`Ghost protects the goddess.`,
`Gorilla's hideout.`,
`Huge black wall.`,
`Huge bug.`,
`In the treasure chest.`,
`On the red ball.`,
`Peek-a-boo Eggman.`,
`Roasted keys...`,
`Scorpions who don't get along.`,
`The nape of the neck.`,
`The only one who is looking the other way...`,
`The place where the bug used to be.`,
`The treasure that you can't open.`,
`Three tails.`,
`Tilted picture.`,
`Treasure chest protected by a scorpion.`,
`Triangle flame.`,
`Two beautiful women on the flame.`,
`Two containers.`,
`Two gatekeepers.`,
`Where the light used to be shinning.`,
`You can see it far away, but you can't see it when you get closer...`,
`Above Omochao.`,
`Between four pillars.`,
`Bug tree.`,
`Bugs on patrol.`,
`Connect the dots.`,
`Dig in the area in front of the scorpion!`,
`Eggman's eye level.`,
`Find the red scorpion hiding in a hole!`,
`Flat Eggman.`,
`Flat scorpion.`,
`Flying fish swimming in the sand.`,
`Four suns looking at each other.`,
`Go up, then go right and left by the wind power.`,
`Gorilla's chase.`,
`Iron protects the safe.`,
`It's floating between the flames...`,
`Merry-go-round.`,
`On the square cliff.`,
`Rescue Chao who is hunted by a scorpion!`,
`Scorpion hiding in a box.`,
`The area that four scorpions are looking at.`,
`The Eggman with a red nose.`,
`The only one who is looking down.`,
`There is a flame, but no light can reach there.`,
`Two bugs who gather in two trees.`,
`Two Eggmans facing each other.`,
`Two guys far away from each other.`,
`Under the red jewel.`,
`Under the red light.`,
`Wandering ghost.`,
`Where the scorpion used to be.`,
`Angry guy.`,
`Angry man.`,
`Big marshmallow.`,
`Fire dance.`,
`Red body.`,
`Sniper.`,
`White family.`,
`Cube-shaped small room.`,
`Shadow of the green flame.`,
`Pale long legs.`,
`Machine's path.`,
`The room with nine flames.`,
`Six bugs lined up on the wall.`,
`In front of the map monitor.`,
`Near the blue light.`,
`The Pyramid Core.`,
`Where the green flame is.`,
`Blue path.`,
`In the container.`,
`On the black iron...`,
`Green treasure chest.`,
`Blue lines on both sides.`,
`Blue stripes on the side.`,
`On the big back.`,
`Big feet.`,
`Where the blue flame is.`,
`In front of a big flame.`,
`Small room with green walls.`,
`Red path.`,
`Green room.`,
`Near the big stone statue.`,
`Buried in the ancient wall painting.`,
`The golden box.`,
`Buried in a wall.`,
`Large room.`,
`Golden box.`,
`Entrance on the right and left side.`,
`The room with no entrance.`,
`Follow the bug...`,
`Green wall.`,
`Small room with four pillars.`,
`Glowing ancient characters.`,
`Above the big flame.`,
`Path with four pillars.`,
`Shadow of the nine flames.`,
`Where the red flame is.`,
`The light never reaches there.`,
`Two red flames.`,
`Small room.`,
`Where the water is.`,
`In the wall.`,
`The pillar that you can't climb.`,
`Bird's head and human body.`,
`You came here once before, right?`,
`Round path.`,
`Under the glowing ancient characters.`,
`The room with two flames.`,
`At the base of the tree.`,
`Five horizontal bugs.`,
`Near the green room.`,
`The bug will show you where the scorpion is.`,
`Altitude of 50 feet. `,
`Room with four pillars.`,
`The room with a treasure chest.`,
`Bird food.`,
`Around eight pillars.`,
`In front of the hourglass.`,
`The room with four pillars.`,
`Under the square hole.`,
`Under the square shadow.`,
`Room where Omochao is.`,
`A ring is buried on one side and a key is buried on the other side. `,
`Two scorpion plates.`,
`In the dark ground.`,
`On the steel grate.`,
`Wandering between the pillars.`,
`Room with the glowing floor.`,
`Blue path. `,
`Small room with a hole near the red room.`,
`Dead end of the blue path.`,
`On the bird statue in the green room.`,
`Underwater area of the blue room.`,
`On the curved path to the red room.`,
`Near the ceiling of the green room.`,
`Near the ceiling of the blue room.`,
`Robot between the red room and the green room.`,
`At the corner of a path to the center of the blue room.`,
`Path to the green room.`,
`Wall of the big machine in the center.`,
`Behind the Eggman stone statue.`,
`Center of the vertical path to the blue room.`,
`Small room on the path to the center of the blue room.`,
`The box in the green room.`,
`Blue room.`,
`Next to the green room.`,
`Long vertical path to the blue room.`,
`Behind the stone statue at the Pyramid Core.`,
`In the stone statue in the Pyramid Core.`,
`By the foot of the stone statue in the Pyramid Core.`,
`On the U-shaped ledge on the path that looks like stairs.`,
`Path to the core to the green room.`,
`In the corner of the path that looks like stairs.`,
`On the map monitor in the blue room.`,
`The room between the red room and green room.`,
`Wall of the switch room on the machine's path.`,
`Small room on the ceiling of the red room.`,
`Near the ceiling of the red room.`,
`Small room on the ceiling of the green room.`,
`In the corner of a path to the red room.`,
`Small step in the green room.`,
`Secret room between the red room and blue room.`,
`Small room on the ceiling of the blue room.`,
`Dead end room on the path to the green room.`,
`In the cage between the red room and the blue room.`,
`Buried above the huge wall decoration by the green room.`,
`Secret room that you can enter from the area next to the blue room.`,
`The room between the red room and the blue room.`,
`Eggman in the green room.`,
`Red room.`,
`Wall by the U-shaped ledge on the blue path.`,
`Behind the lion statue in the red room.`,
`Wall near the ceiling shaped like stairs in the blue room.`,
`Small underwater room in the blue room.`,
`Dig into the three scorpion plates on the path near the red room.`,
`Wall of the red room.`,
`Between three lights in the blue room.`,
`The vertical long path to the blue room.`,
`The container on the pillar in the Pyramid Core.`,
`Wall by the entrance to the green room from the Pyramid Core.`,
`Where the Hammer Gloves used to be.`,
`Under the trap of the Pyramid Core.`,
`Watch out for the trap on the path to the green room.`,
`Stone statue at the Pyramid Core.`,
`Green path with four pillars.`,
`Dig in the area following the scorpion's direction...`,
`Under the scorpion plate on the wall of the core area.`,
`Glide to the Eggman statue from the pillar in the center...`,
`Secret room between the red room and green room.`,
`Dig into the eye of the Eggman mark on the blue path!`,
`Dig into the scorpion under the trap set on the core!`,
`Center of the four Eggman symbols on the red path.`,
`Machine's path to the red room.`,
`Secret room between the red room and the green room.`,
`Center of the green room.`,
`Suspended circle over the Pyramid Core.`,
`Under the moving trap on the machine's path.`,
`The entrance to the red room coming from the Pyramid Core.`,
`At the corner of the red path that looks like stairs.`,
`Dig in the center area of the blue room.`,
`Wall near the ceiling that is shaped like stairs in the blue path.`,
`Next to the red room.`,
`Machine's path to the blue room.`,
`In the middle of the narrow path to the center of the green room.`,
`In the ground near the blue room. Look for the bug on the ceiling.`,
`Center of the moving trap on the machine's path.`,
`Path to the center of the green room.`,
`Path connected to the red room and the blue room.`,
`Robot on the path to the center of the blue room.`,
`Huge ghost in the Pyramid Core.`,
`Path connected to the red room and blue room.`,
`Huge ghost on a path to the center of the green room.`,
`A container that doesn't float.`,
`A container within a container.`,
`A fast rotating meteorite.`,
`Above a blue moon in front of a tank.`,
`Between the floating containers.`,
`Between the noisy machines.`,
`Between the rotating beacons.`,
`Drilling tower.`,
`Hot molten lava below.`,
`In a wooden box.`,
`In front of a big door that never opens.`,
`In front of the shortcut rocket.`,
`In front of the weight elevator.`,
`In the center of a triangle star.`,
`In the floating containers.`,
`Inside a container which is behind a container.`,
`Near a moon with a rotating beacon.`,
`Next to the rocket pointing at the ARK.`,
`On a rotating beacon above a blue moon.`,
`On something strong.`,
`The ARK's huge storage area.`,
`The huge shutter on the steel tower.`,
`Two huge containers.`,
`Where two stone platforms are joined.`,
`Zero point five.`,
`A moon and a missile.`,
`A star and a missile.`,
`A star between three arches.`,
`A switch in a cage.`,
`At the base of the rotating beacon.`,
`Behind something powerful.`,
`Between the moon and stars.`,
`Black boxes on the black platform.`,
`Dig into a small meteorite.`,
`Floating stone above a moon.`,
`Forget to put it in a big container?`,
`Lonely moon.`,
`Next to a rocket aimed at the ARK.`,
`On top of the steel drilling tower.`,
`Steel guardian.`,
`The ARK's huge container.`,
`The first stage.`,
`The highest rotating beacon.`,
`Tic-tac-toe!`,
`Too heavy to float.`,
`Twin stars.`,
`Two against one!`,
`Two stars and one moon.`,
`Under a star.`,
`Upper the floating tank!`,
`A container at the top of the ARK.`,
`A glimpse of the meteorite.`,
`At the top of the tip of the ARK.`,
`Behind a star.`,
`Between two rotating beacons.`,
`Center of a square shadow.`,
`Circle the rotating beacon.`,
`Floating around the moon.`,
`Floating in front of three tanks next to each other.`,
`Jump from the star!`,
`Middle of the rotating beacon.`,
`Moving around in front of the one floating tank.`,
`Moving around the ARK's huge storage area.`,
`Moving smoothly at the top of the ARK.`,
`Next to a mini-steel beam.`,
`Next to the mini-steel beam.`,
`Powerless by itself.`,
`Shadow of a floating tank.`,
`Surrounded by spinner containers.`,
`The cage in a container.`,
`Try digging while watching the moon.`,
`Try digging while watching the stars.`,
`Use a meteorite that flies when you hit it!`,
`Wandering between the second and third levels.`,
`A GUN's machine is protecting the ARK.`,
`Dangerous liquid.`,
`Dangerous water drops.`,
`Evil water drops.`,
`Something sealed.`,
`A big floating platform.`,
`Between the inverted blue tower and the steel tower on the ground.`,
`A lot of small meteorites.`,
`A lot of small meteorites`,
`Dense meteorite area.`,
`On the GRAY ground below.`,
`On the YELLOW ground.`,
`On a square stone platform.`,
`A floating platform.`,
`Pyramid-shaped base.`,
`A floating square stone platform.`,
`The tip of the ARK.`,
`On the huge suspended containers.`,
`On a container.`,
`YELLOW ground.`,
`Near the steel tower on the pyramid-shaped base.`,
`Suspended above the YELLOW ground.`,
`Suspended above the GRAY ground you see below.`,
`The platform below the ARK.`,
`A lot of floating platforms.`,
`A lot of small floating meteorites.`,
`A lot of meteorites`,
`A lot of meteorites.`,
`Boundary of the RED and YELLOW ground.`,
`A square stone platform.`,
`A big platform with six circles.`,
`RED ground.`,
`In a storage container.`,
`A big platform with six circles`,
`Near the pyramid-shaped base.`,
`A floating big platform.`,
`A part of the ARK.`,
`Under the group of small meteorites.`,
`Down blow.`,
`In a container on a platform with six circles.`,
`In the three huge containers that are next to each other.`,
`Try breaking the rotating meteorite near the square stone platform...`,
`On a moon symbol located on two connected square stone platforms.`,
`The fourth big floating platform from the bottom.`,
`Near the moving weight.`,
`Behind loading dock "0-1".`,
`On a tower that contains a moving tube inside.`,
`In front of loading dock "0-2".`,
`A wooden container next to the yellow bulldozer on the GRAY ground.`,
`In front of the steel tower.`,
`Near the rocket in the big steel tower on the ground.`,
`In front of the moving weight on a square stone platform.`,
`In the middle of a star symbol on the GRAY ground.`,
`In the right one of the two huge containers.`,
`On a square stone platform with one rotating beacon.`,
`On top of a big platform with six circles.`,
`On the yellow bulldozer which is on the GRAY ground below.`,
`A square stone platform near the huge containers.`,
`On one of the huge containers.`,
`Around the base of the big steel tower on the ground.`,
`On the huge containers next to each other.`,
`On a steel beam between two connected stone platforms.`,
`In front of loading dock "0-5".`,
`Dig under the moon symbol on a platform with a missile.`,
`Dig under the star symbol on a platform with a missile.`,
`Under the star symbol near the three arches above the RED ground.`,
`Dig near the switch in a cage.`,
`Dig under the beacon sticking out of the middle of a platform.`,
`Under a moon symbol behind the yellow bulldozer.`,
`Dig between the moon and star symbols on a square platform.`,
`On a platform near the inverted blue tower.`,
`In a small meteorite above a spring above a star symbol.`,
`In a stone on a moon symbol on the highest platform.`,
`Dig under the beacon in front of the pyramid-shaped base.`,
`Dig in the center of the stone platform with one moon.`,
`On top of a platform with six circles.`,
`Try knocking the huge meteorite off loading dock "0-5".`,
`In the left one of the two huge containers.`,
`Under a moon symbol in front of loading dock "0-1".`,
`On a floating stone platform near the inverted blue tower.`,
`Try breaking a container in the steel tower on the ground...`,
`Under a platform with six circles.`,
`Under two star symbols next to each other above the GRAY ground.`,
`Two star symbols and one moon symbol on a platform. Dig under moon.`,
`Try digging behind a balcony with a star on an inverted blue tower.`,
`On the platform above the lonely floating container.`,
`On a platform above the lonely floating container.`,
`On the two huge containers at the bottom of the inverted blue tower.`,
`Inside a meteorite you see using a rocket to the ARK's center.`,
`By the red tip of the inverted blue tower.`,
`Dig between two beacons on a square platform with a spring...`,
`Try digging in the middle of a moving weight...`,
`Rotating and moving on the square stone platform with a spring.`,
`Moving on a square stone platform.`,
`A floating big platform above two huge containers.`,
`Farthest meteorite you see after using the spring.`,
`Biggest and fastest rotating meteor you see after using the spring.`,
`Smallest and fastest rotating meteor you see after using the spring.`,
`Buried somewhere surrounded by four beacons by loading dock "0-5".`,
`Buried in a stone platform with steel beams that go nowhere...`,
`Moving between the three huge containers next to each other.`,
`Use the rocket to go up, then get to the left side of the platform.`,
`Dig next to a steel beam sticking out of a wall...`,
`Dig next to the steel beam sticking out of a wall...`,
`Dig under the moving weight in front of the bulldozer...`,
`Dig in the shadow of a floating tank on a square stone platform.`,
`Dig in the shadow of a floating tank under three arches.`,
`On a platform with a lot of black containers at the top of the ARK.`,
`Use the Triple Punch Upper!`,
`Dig under a moon on the wall next to a big platform with a rocket.`,
`Dig under a moon next to a big platform without a floating container.`,
`Dig under a moon on the wall next to a big platform with a steel beam.`,
`Dig under a star on the wall next to a big platform with a rocket.`,
`Dig under a star on the wall next to a big platform with a steel beam.`,
`Dig under a star next to a big platform without a floating container.`,
`Try throwing a meteorite at the blinking door...`,
`Moving up and down along the pillar inside the steel tower.`,
`Destroy GUN's machine at the tip of the ARK.`,
`Defeat the water enemy!`,
`Destroy the water enemy at the tip of the ARK.`,
`Water enemy on a platform with a spring near huge containers.`,
`Try knocking the meteorite into a blue box on loading dock "0-1".`,
`A coconut?`,
`A coconut?.`,
`A jar surrounded by three stakes.`,
`A lot of square faces.`,
`A red flower in the water?`,
`Behind the pillar plants.`,
`Behind the rubble.`,
`Behind the water plant.`,
`Beneath the stone face apartments.`,
`Between the suns facing each other.`,
`Blue and white "V".`,
`Blue and white striped pillar.`,
`Blue and white striped tunnel.`,
`Blue box surrounded by four stakes.`,
`Blue box.`,
`Blue striped head.`,
`Bull's eye!`,
`Butterfly's treasure.`,
`By the far away pond.`,
`By the foot of a shell.`,
`By the giant's chair.`,
`Circle around the small sun.`,
`Circle around the tilted pillar.`,
`Dry Lagoon thermometer.`,
`Emerald leaf.`,
`Enchanted pillar.`,
`First floor of the stone face apartments.`,
`Fish food.`,
`Floating with butterflies.`,
`Forgotten little boat.`,
`Go up and down the stairs.`,
`Green pool.`,
`GUN's guard for the storage area.`,
`GUN's guard of the storage area.`,
`GUN's jar?`,
`GUN's mini storage area.`,
`GUN's storage area.`,
`Huge screen.`,
`In between the mini pillars.`,
`In front of the white bricks.`,
`In the corner of the room covered with hieroglyphics.`,
`Jar storage place.`,
`Moving between the big and small pillars.`,
`Oasis jail`,
`Oasis jail.`,
`Offering.`,
`On a hexagon pillar.`,
`On the biggest turtle shell.`,
`On the head.`,
`On the ledge with three red circles`,
`On the ledge with three red circles.`,
`On the tilted pillar.`,
`On top of a palm tree.`,
`Outside a jail cell.`,
`Plants in the shade.`,
`Protector of the jar.`,
`Protector of the pond.`,
`Razor plant.`,
`Red flowers and red pillar.`,
`Second floor of the stone face apartments.`,
`Second floor rooftop of the stone face apartments.`,
`Stone monument of the sun.`,
`Stone statue's treasure.`,
`Tears of a giant.`,
`The place where water comes from.`,
`The pool in front of the wall.`,
`Turtle's path.`,
`Turtle's tunnel.`,
`Two huge pillars.`,
`Under a chin.`,
`Under the star in the GUN's storage area.`,
`Under the turtle's face.`,
`Underneath the platform with four stakes.`,
`Underwater balcony .`,
`Underwater balcony.`,
`V shape.`,
`Near a leaf.`,
`On the grass.`,
`In the water.`,
`Big oasis.`,
`On a stone.`,
`A narrow place.`,
`On the stone.`,
`Red circle.`,
`Where there are some butterflies.`,
`Small oasis.`,
`In the stone.`,
`On a hexagonal pillar.`,
`The three stone faces.`,
`In a valley.`,
`Above the small oasis.`,
`Near the water.`,
`A high place`,
`In a jar.`,
`On the palm tree by the three stone faces.`,
`On the palm tree near the small oasis.`,
`In a jar by the wall near the small oasis.`,
`On a path with many square blocks with eyes.`,
`Behind the spring.`,
`Between two spring by the pool statue.`,
`In the grass on the ledge sticking out over water.`,
`Near the big leafy water plant at the bottom of the big oasis.`,
`Near the large leaf at the bottom of the big oasis.`,
`Under the moving weight near the pool statue.`,
`Between the tall pillar and ledge in the big oasis.`,
`On the blue pillar in front of the pool statue.`,
`Behind the blue pillar in front of the pool statue.`,
`Behind the buried pillar at the bottom of the big oasis.`,
`In a jar inside the tunnel in the oasis jail.`,
`In the tunnel in the oasis jail.`,
`In the box on the platform sticking out above the water.`,
`In a blue box near the tall pillar.`,
`On the head of the pool statue.`,
`On the head of a sitting statue in the small oasis.`,
`In front of a red circle on a tall pillar in the small oasis.`,
`In the center of the ring in the sky above the small oasis.`,
`Path to the three stone faces.`,
`Behind a floating turtle.`,
`Next to the chair of the sitting statue in the small oasis.`,
`Near the red circle on top of the tall pillar.`,
`Grab the turtle to take you there... You may find it.`,
`Next to the tall pillar and moving.`,
`On the grassy ledge above the big oasis.`,
`On a pillar that the three stone faces are looking at.`,
`On the pillar near the three stone faces.`,
`In a square block with eyes near the pool statue.`,
`On the water near the oasis jail.`,
`On the red pillar in front of the three stone faces.`,
`On the little boat by the three stone faces.`,
`Floating on the path near the pool statue.`,
`In a square pond above the small oasis.`,
`The GUN's machine near many containers has it.`,
`GUN's machine on the path.`,
`In a jar among a lot of containers.`,
`In a square block with eyes near containers in the small oasis.`,
`On many containers.`,
`In front of the huge wall painting near the small oasis.`,
`In the middle of the circle of stakes in the big oasis.`,
`Between the tall pillar and the white bricks.`,
`In the oasis jail.`,
`In a jar on the path above the small oasis.`,
`Floating on the path to the three stone faces.`,
`Grab the turtle in the water. It may take you somewhere.`,
`At the base of a high pillar.`,
`On top of the red pillar.`,
`On the roof of the pond where turtles swim.`,
`On a wall with three stone faces.`,
`Screw Kick in front of the skull.`,
`In a jar on the ledge above the big oasis.`,
`On the ledge above the big oasis.`,
`Screw Kick into the center of the ledge with three stakes.`,
`Near the fence by the oasis jail.`,
`Near the foot of the sitting statue in the small oasis.`,
`In the plants by the foot of the sitting statue.`,
`The GUN's machine on the path.`,
`The GUN's machine on the path above the small oasis.`,
`In the plants on the path above the small oasis.`,
`Under two red pillars on the path to the three stone faces.`,
`In a blue box near the front of the pool.`,
`Above the stone pillar with a red circle by the water.`,
`On a square box that the pool statue is holding.`,
`In the box held by the sitting statue.`,
`Under the left eye of one of the three stone faces.`,
`Above the hole at the bottom of the big oasis.`,
`Above the small pool in front of the wall painting.`,
`In front of the red pillar at the bottom of the big oasis.`,
`Tunnel entrance where water comes out of at the bottom of the oasis.`,
`On the huge red pillar on the path to the three stone faces.`,
`Under the three stone faces.`,
`A jar under the spring above the small oasis.`,
`Deep down under the roof of the pond where turtles swim.`,
`Between the ledge sticking out of the wall and the water's edge.`,
`On the underwater shelf in the big oasis.`,
`Under the platform sticking out of the wall at the bottom of the pond.`,
`Between the two trunks of the palm tree.`,
`A black container.`,
`A dark room.`,
`A glowing red square.`,
`A place surrounded by black and yellow.`,
`A quiet place.`,
`A red pillar triangle.`,
`A room with hieroglyphics.`,
`A shadow that stretches from the bottom to the top.`,
`A skull message.`,
`A skull.`,
`A thick wall.`,
`Above the entrance.`,
`Black bird in the shadow. `,
`Blue-eyed Eggman.`,
`Brown between black.`,
`Center of the ring.`,
`Chao sign on the floor.`,
`Chao symbol on the wall.`,
`Chipped petal.`,
`Condor's egg.`,
`Dark Chao.`,
`Dark red and white stripes.`,
`Dark Sonic.`,
`Fear of heights.`,
`First place you landed.`,
`Flames facing each other.`,
`Floating in the stream...`,
`Follow the line on the wall.`,
`Follow the rings.`,
`Four pillars.`,
`Full-scale eye...? `,
`Glowing hieroglyphics.`,
`Golden condor.`,
`Hand in the center.`,
`Hidden ancient wall painting.`,
`Holy altar.`,
`Holy sacrifice.`,
`Hot Chao...`,
`Huge shadow room.`,
`In the center of the "X".`,
`In the middle of the room.`,
`In the shadow of the scurrying bug.`,
`Invisible container.`,
`King and the servant.`,
`Life sentence...`,
`Omochao and Eggman.`,
`On a needle.`,
`On the scorpion.`,
`On the white Eggman mark.`,
`Play volleyball with a mouth???`,
`Red and silver moving back and forth.`,
`Red warrior.`,
`Riding the golden condor.`,
`Second after next to the stone ring.`,
`Semi-dark Eggman.`,
`Six Eggman marks?`,
`Six white eggs.`,
`Skull's room.`,
`Skulls facing each other.`,
`Sleeping under a coffin.`,
`Slowly swimming...`,
`Snake flame.`,
`Stone walls on the right, left and above.`,
`The condor spreads its wings.`,
`The Foreman???`,
`The head of a condor.`,
`The head of the condor.`,
`The hexagonal ceiling.`,
`The second room.`,
`The skull is looking at you through a crack.`,
`Three hands.`,
`Three snake brothers.`,
`Three triangles.`,
`Two beautiful women with fish faces.`,
`Two faces.`,
`Two pair of different length legs.`,
`Two pairs of different length legs.`,
`Two smelting furnaces.`,
`Under the belly.`,
`Under the hieroglyphics.`,
`Under the low flame.`,
`Under the scorpion.`,
`Under the tail.`,
`Under the treasure.`,
`Upside down stairs.`,
`Wandering ghost...`,
`White middle finger.`,
`Wings but can't fly.`,
`Yellow head.`,
`Snake Altar.`,
`Green path.`,
`Egg Fish Chamber.`,
`A room with no flames.`,
`Near the Egg Fish Chamber.`,
`A room with eight flames.`,
`Condor's room.`,
`Egg Scorpion Chamber.`,
`Blue like Chao.`,
`A room with four flames.`,
`Red pillar's shadow.`,
`Shadow of the machine.`,
`Shadow of the longest pillar.`,
`Blue like Sonic.`,
`Out of reach of the light.`,
`Room with glowing hieroglyphics.`,
`Moving back and forth between the flames.`,
`A small room with four walls covered with hieroglyphics.`,
`A place surrounded by flames.`,
`Egg Snake Chamber.`,
`A path with four pillars.`,
`Iron wall.`,
`In a treasure chest.`,
`Near the Egg Snake Chamber.`,
`Something that the snake is looking at.`,
`In the middle of three flames.`,
`Poolside.`,
`Green flame.`,
`A flattened stone plate.`,
`In a container by the side of a small room with an altar.`,
`Near a ceiling in a small room by a path.`,
`Near the ceiling in a small room by a path.`,
`In the middle of a room with containers.`,
`A container in the back of the Egg Fish Chamber.`,
`A container in a room with bars.`,
`Treasure chest on the ceiling of the Egg Fish Chamber.`,
`Behind the Egg Snake statue.`,
`Stair-shaped ceiling in the Egg Snake Chamber.`,
`By the neck of a snake attached to the altar.`,
`Buried above the green flame.`,
`Underwater chamber in the Egg Fish Chamber.`,
`Hieroglyphics written in the shadow of a pillar in the Egg Fish Chamber.`,
`Dig into the wall painting on an iron door.`,
`Under the Eggman mark on the floor.`,
`A dot mark on a floor of the Egg Fish Chamber.`,
`A dot-shaped hieroglyphic written on a narrow path.`,
`Dig under the wall decoration above the Egg Snake statue.`,
`Dig under the wall decoration in the Egg Scorpion Chamber.`,
`Dot-shaped hieroglyphics in the shadows in the Snake Altar.`,
`In a wall covered by shadows in the Egg Scorpion Chamber.`,
`Shadow of a pillar in the Snake Altar reveals Sonic-like hieroglyphics.`,
`Hieroglyphics written behind a wall in the Egg Fish Chamber.`,
`The monkey robot on the pillar.`,
`Buried between two pillars.`,
`Dig between two flames on the wall.`,
`Underwater room in the Egg Fish Chamber.`,
`On the Egg Scorpion statue.`,
`On the eight pillars near the Snake Altar.`,
`The area on top of the pillar on a narrow path.`,
`In a container in the corner of a room.`,
`Left eye of the Egg Fish statue.`,
`Suspended above a curved path.`,
`A coffin in a small room by a path.`,
`A coffin on the ceiling of the Egg Scorpion Chamber.`,
`Dig near the wall decoration on the U-shaped ledge.`,
`On the Egg Fish statue.`,
`In a coffin on the U-shaped ledge.`,
`Do a Screw Kick between two flames.`,
`By the small red flame next to the Snake Altar.`,
`In a container by a wall of a small room with an altar.`,
`A wall in the Snake Altar room.`,
`Suspended above the Snake Altar.`,
`Climb the pillar.`,
`The monkey robot next to the Egg Fish Chamber.`,
`Dig into the Eggman under the Egg Scorpion statue.`,
`Around the Snake Altar.`,
`By the wall in the small room.`,
`A flame room near the Snake Altar.`,
`A path next to the Egg Fish Chamber.`,
`Inside Eggman's robot.`,
`A small room next to the Egg Snake Chamber.`,
`Under the container in back of the Egg Fish Chamber.`,
`Buried under the Eggman symbol.`,
`Dig into the Eggman mark on the machine's path.`,
`Small room on the ceiling of the Egg Scorpion Chamber.`,
`Buried in a wall of a small room by a path.`,
`Under the floor of a small room in the Egg Scorpion Chamber.`,
`Inverted stairs in the Egg Fish Chamber.`,
`U-shaped ledge on a narrow path.`,
`In the container on the U-shaped ledge.`,
`In the corner of the room.`,
`A treasure chest on the ceiling in the Egg Snake Chamber.`,
`Wall decoration in the Egg Snake Chamber.`,
`On the Egg Snake statue.`,
`On a chest in the Snake Altar room.`,
`Next to a chest on a narrow path.`,
`The U-shaped ledge on a narrow path.`,
`Dig near the small step in the center of the room.`,
`Dig into the center of a wall painting.`,
`Chest of the Egg Snake statue.`,
`Under the shadow of the short pillars among four pillars.`,
`Buried between two huge flames.`,
`Dig near the entrance and pool in the Egg Fish Chamber.`,
`Small room next to the Egg Snake Chamber.`,
`A path next to the Egg Snake Chamber.`,
`Buried under the light on the path with four pillars.`,
`Under a stone plate near the Snake Altar.`,
`Buried between the back and the tail of the Egg Scorpion statue.`,
`Under the floor beneath a chest on the ceiling in the Egg Fish Chamber.`,
`A ceiling that looks like stairs.`,
`A path that looks like stairs near four pillars.`,
`A small room next to the Egg Scorpion Chamber.`,
`On the fin of the Egg Fish statue.`,
`A place where you use the most electricity.`,
`A place where you use the most electricity. `,
`A place which is protected by lasers.`,
`A place which is protected by spikes.`,
`A place which is protected lasers.`,
`Air conditioner of the Security Hall.`,
`Everyone has seen it at least once before...`,
`Hiding up there...`,
`If you kick it, it will get very mad and turn red.`,
`In a cold box.`,
`In the tank.`,
`Invincible guard.`,
`Invisible rings mark the spot.`,
`Lonely at work.`,
`Lonely door.`,
`Lost child.`,
`Near the letter box.`,
`Next to a cardboard box.`,
`Next to the a cardboard box.`,
`Next to the cardboard boxes.`,
`On a big box.`,
`Piled up containers.`,
`Protect "Blue."`,
`Protect "Blue".`,
`Red "X".`,
`Riding on the ____?`,
`Shows up once in a while.`,
`Six safes.`,
`Taking a nap...`,
`The letter "L".`,
`The next one is empty.`,
`The one above is empty.`,
`The one below is empty.`,
`Three cylinders.`,
`Tilted laser.`,
`Two ____ looking down below...`,
`Two containers facing each other.`,
`Two-colored container.`,
`Under the square air duct.`,
`Under the unbreakable container.`,
`Useless _____.`,
`Useless safe.`,
`With a cardboard box.`,
`With a lot of money.`,
`Yellow rectangle.`,
`You can see it from the bottom, but can't get to it from the bottom.`,
`You can see it, but you can't get it.`,
`C block.`,
`Dead end.`,
`A block.`,
`Very carefully...`,
`Four safes.`,
`BLUE floor.`,
`A cardboard box above.`,
`Dancing money.`,
`Under the laser.`,
`By the wall.`,
`B block.`,
`Dancing wind.`,
`Under the cardboard box.`,
`YELLOW floor.`,
`RED floor.`,
`Obstacle ahead.`,
`Four bodyguards.`,
`Sometimes in "A" block, sometimes in "B" block.`,
`Watch out for the red laser.`,
`Block the intruder from the air.`,
`A block. `,
`On the fence.`,
`A container in the middle.`,
`The place you often go by.`,
`In the GUN's robot.`,
`At the end of "C" block.`,
`Between the boxes.`,
`The floor in the middle of the switch room.`,
`YELLOW "A".`,
`At the end of "A" block.`,
`BLUE "A".`,
`BLUE "C".`,
`On the air duct on the YELLOW floor.`,
`In the spiked car.`,
`On the RED switch.`,
`Switch room.`,
`In the corner of "A" block and "B" block.`,
`In the corner of "B" block and "C" block.`,
`On the square air duct.`,
`Below the square air duct.`,
`A tank near the BLUE switch.`,
`A tank in "C" block.`,
`A safe in "A" block.`,
`Entrance to the RED switch.`,
`A safe in "C" block.`,
`In the sky above the switch room.`,
`Between "B" block and "C" block.`,
`A safe in "B" block.`,
`In the sky above "B" block.`,
`Between "A" block and "B" block.`,
`The box for the scrapped weapons in the switch room.`,
`YELLOW "B".`,
`In the sky above "A" block.`,
`Near the ceiling in "A" block and "B" block.`,
`A small room with a rocket.`,
`On a large box.`,
`Entrance to the switch room.`,
`Near the ceiling in "B" block.`,
`Passageway to the upper room.`,
`A safe in a cage.`,
`In the sky above "C" block.`,
`? ... gniworg neerg htiw noom tnecserc`,
`1 on enihcam fo gel eht fo pot eht`,
`3 on enihcam fo gel eht fo pot eht`,
`Burning rock seed.`,
`dap gnihcnual elissim lanogatco`,
`diuqil live`,
`dnats eulb eht no ymene eulb eht`,
`edahs eht ni kcor neerg eht`,
`edisni toh s'ti`,
`egarots yssem`,
`eiriarp eht no rats ylenol`,
`elcric thgil eulb`,
`elcric thgil wolley`,
`eluspac eht fo pot eht`,
`erauqs der`,
`esab eht ta sreniatnoc kcalb fo hcnub a`,
`esuoh ylenol`,
`etiroetem eht evoba xob gninnips eht`,
`etiroetem ytivarg eht fo mroftalp gnitaolf`,
`foor a rednu rats eht`,
`gel 2.on`,
`giniliec eht no noom a`,
`gnihtemos neewteb noom eht`,
`gninepo na tuohtiw reniatnoc eht`,
`gninepo on htiw reniatnoc`,
`gnitaolf ton si taht reniatnoc eht`,
`htrae ot rats tseraen eht`,
`kcik wercs kciuq`,
`kcor a no gniworg lewej a`,
`krad eht ni thgil ylenol`,
`lian der`,
`Liquid creature in the crater.`,
`lwob a ni neerg`,
`Missile watchman.`,
`mroftalp eht fo esab eht`,
`mroftalp wolley yrev`,
`namhctaw gninrub a yb rats`,
`no senihs thgil der eht taht rats eht`,
`noom ddo`,
`noom eht raen xob gnitaolf eht`,
`noom suoregnad`,
`pu worg t'ndid that thgil eht`,
`rats gnikcits`,
`rats souregnad`,
`rehtag sthgil eht fo lla erehw`,
`renaitnoc egarots eht stcetorp that enihcam eht`,
`reniatnoc a nihtiw reniatnoc a`,
`reniatnoc deroloc eerht`,
`reniatnoc egarots eht stcetorp that enihcam eht`,
`reniatnoc gniylf`,
`renwo s'etiroetem eht fo esuoh eht`,
`seert eht ees ot tserof eht ot esolc ot`,
`seloh htiw retarc`,
`sgel eerht htiw 1 .on enihcam`,
`sgel eerht htiw 3 .on enihcam`,
`sgel eerht htiw enihcam eht fo relleporp`,
`sgel eerht htiw senihcam eht neewteb ni`,
`slian der eht neewteb`,
`snoom owt neewteb`,
`ssarg eht no xob nedoow gnicnad`,
`sthgil der yb dednuorrus xob a`,
`syug llat eht neewteb`,
`tghiew repap eguh`,
`tghil ylenol and das`,
`thgil derit`,
`thgil detlit`,
`thgil detlit eht fo esab eht ta`,
`thgil eht rednu rats eht`,
`thgil gnorw`,
`trac retarc`,
`wolley ni eulb`,
`xob kcalb eht rednu`,
`ynoclab reniatnoc kcalb`,
`ynoclab thgil der`,
`ynoclab thgil eulb`,
`ynoclab thgil wolley`,
`ynoclab wolley eht fo namhctaw`,
`The highest place.`,
`Where it's not tilted.`,
`A flat place.`,
`A place where it's not flat.`,
`retarc eht ni erutaerc diuqil`,
`A low place.`,
`A meteorite with no gravity.`,
`Short meteorite.`,
`It's not the dented area.`,
`The smallest meteorite.`,
`The meteorite with no gravity.`,
`Meteorite without grass.`,
`The biggest meteorite.`,
`Big meteorite.`,
`Where there is no green.`,
`Far away from an inverted tower.`,
`On the ground.`,
`It's not a narrow and long place.`,
`The lowest place.`,
`namhctaw elissim`,
`The place you can't dig.`,
`A place that is not flat.`,
`etiroetem eht fo mottob eht`,
`Wide open area.`,
`The place that is not small.`,
`sdap gnihcnual elissim eerht`,
`A place that is not narrow.`,
`A place that is not small.`,
`A very high place.`,
`etiroetem eht dnuora seog that niart eht`,
`ynoclab reniatnoc eulb`,
`gninepo na touhtiw reniatnoc eht`,
`Don't dig behind the moon symbol on the lowest platform with green rocks.`,
`Don't dig under the sign "1" of the pipe machine on the capsule meteorite!`,
`Don't dig under the sign "3" of the pipe machine on the capsule meteorite!`,
`In the burning red rock on the floating meteorite.`,
`It's not on a platform you can reach using a rocket on a crater meteorite.`,
`An enemy on a big platform near a blue tower doesn't have it.`,
`Don't bother the water enemy on the platform with a blue light below!`,
`Don't dig in the area above the green rockes in the shadow of the flying train.`,
`It's not in the burning rock above the floating meteorite.`,
`It's not in the two connected storage containers which are floating.`,
`Don't dig under the star symbol on the meteorite with grass!`,
`It's not the area near the farthest blue light on the biggest meteorite.`,
`It's not near the yellow light on the round meteorite.`,
`It's not the top of the capsule under the capsule meteorite.`,
`Under a blinking red light at the top of an inverted tower.`,
`It's not between the floating black containers down below.`,
`It's not next to the green stone by a hut on the floating meteorite.`,
`It's not in front of the building on the biggest planet.`,
`In the floating white box above the floating meteorite.`,
`It's not on the glowing square stone which is floating.`,
`Don't dig under a star symbol under a building on the round meteorite!`,
`It's not on the top of the machine with pipes on the capsule meteorite.`,
`Don't dig under a moon symbol under the capsule meteorite.`,
`Don't dig into a moon symbol on a platform with many red lights.`,
`Not between a storage container below on the inverted tower.`,
`It's not on the connected containers under the inverted tower.`,
`It's not a box on a platform with a red light on an inverted tower.`,
`Don't dig into the star symbol on the lowest platform!`,
`It's not far away from a green rock above a floating meteorite.`,
`Far away from a green rock above a floating meteorite.`,
`Don't dig under the lonely light on the floating meteorite.`,
`It's not the area that is glowing on the capsule meteorite.`,
`Don't defeat the water enemy on the meteorite with a crater!`,
`It's far away from the green stone above the floating meteorite.`,
`It's not an enemy you can reach using a rocket on a crater meteorite.`,
`It's not in the white box that the cage is on top of.`,
`It's not on a platform with yellow lights on the round meteorite.`,
`aera lortnoc fo tou eht ni mroftalp eht`,
`Don't dig near a star on the lowest platform with burning meteorites.`,
`Don't dig in different star symbols on a platform wall with blue lights.`,
`Don't dig into different moon symbols on a platform wall with red lights.`,
`It's not in a floating white box behind the moon symbol.`,
`Don't dig into a moon symbol near a steel ball with blue lights.`,
`Don't dig under a moon symbol near a trap on the capsule meteorite!`,
`Don't dig under the only short light high up on the floating meteorite.`,
`Don't dig into a star symbol on a wall of a platform with six circles.`,
`Don't dig under a star on a platform with many blue lights.`,
`Don't dig under a star symbol on a platform with many blue lights.`,
`Don't dig near a star next to the spheres on the platform by the capsule meteorite.`,
`It's not in a wall under a star symbol on a yellow platform with lights.`,
`Not under a black container above a platform with a red light tower.`,
`It's not in the box in the storage container with a yellow light.`,
`ynoclab lhgil der eht morf renaitnoc kcalb nellaf eht`,
`It's not in the storage container with blue lights.`,
`It's not on the storage container with yellow lights.`,
`It's not in the box in the storage container with a red light.`,
`Don't defeat GUN's machine on the connected storage containers!`,
`It's not in the floating box above a platform on an inverted tower.`,
`It's not under the building on the round meteorite.`,
`It's not below the starting point.`,
`It's not the base of a growing stone above the dented meteorite.`,
`It's not on the machine with three pipes on the capsule meteorite.`,
`Not between machine No.1 and No.2 with pipes on the capsule meteorite.`,
`Don't break the wooden box between platforms on the capsule meteorite.`,
`Don't dig between the two moons above the lowest platform!`,
`It's not in a floating wooden box above the capsule meteorite.`,
`It's not in a box on a platform under the inverted tower.`,
`It's not between two lights on the capsule meteorite.`,
`Don't dig in the center of the lowest platform with the moving weight.`,
`It's not the fallen yellow light on the round meteorite.`,
`At the base of a long tilted light on the floating meteorite.`,
`Don't dig at the base of the long light near the green rock!`,
`It's not under a moon on a yellow platform near an inverted tower.`,
`Don't dig under the blue light on the round meteorite!`,
`It's not near the lonely blue light on the round light.`,
`It's not under the moon on the yellow platform near the hanging blue structure.`,
`Don't dig under the container in high up on the floating meteorite.`,
`It's not on a platform with a black container on an inverted tower.`,
`It's not under the platform with a red light on the inverted tower.`,
`It's not on the platform with a red light on an inverted tower.`,
`It's not on the platform with a blue light on an inverted tower.`,
`You can't use a rocket on a platform with a yellow light tower.`,
`It's not on the platform with a yellow light on an inverted tower.`,
`It's not GUN's machine on a platform with a yellow light by a blue tower.`
]

const copList = [" There always seems to be a lot of police around when you don't need them!"];

const trumpList = [" Mr. President, this is a national crisis."];

const questionList = [ "If I tell you, will you marry me?"];

const shadowList = [" Sayonara, Shadow the Hedgehog...",
  " He was who he was. A brave and heroic hedgehog who gave his life to save the planet. Shadow the Hedgehog...",
  " The reason I'm here is because of that fake hedgehog"
];

const sonicList = [" That blue hedgehog again, of all places.",
  " What you see is what you get. Just a hedgehog that loves adventure.",
  " I found you...faker.",
  " I'll make you eat those words."
];

const emeraldList = [" The master emerald contains special powers that neutralize the energy of the chaos emerald. That makes it very powerful.",
  " The Chaos Emeralds are like magnets...they have the power to attract each other.",
  " Long time no see treasure hunter. Did you find MY Emeralds?",
  " Hand over the Chaos Emerald, slowly, and then we will talk about your girlfriend! That is if you really care for her...",
  " You thought you could trick me with that fake Emerald, didn't you?",
  " I will get the Chaos Emeralds, use the machine to dominate the world and build a legacy of my own!",
  " I can't believe that I'm trapped inside this locked safe with the Chaos Emeralds!",
  " Put the Emerald down right there and BACK OFF!"
];

const defaultList = [" You're not even good enough to be my fake.",
  " I'll make you eat those words.",
  " Letting Knuckles pilot the shuttle over here was more dangerous than you'll ever be.",
  " This place sure feels haunted.",
  " Look, half of the moon is gone!?",
  " There always seems to be a lot of police around when you don't need them!",
  " Tornado...Transformation!",
  " Hah, hah, hah! Citizens of earth, lend me your ears and listen to me very carefully!",
  " Our financial communities are impacted and our satellite communications are down.",
  " I won't bore you with all the details since I know you are a very busy man. ",
  " Huh...that was pretty rough.",
  " What are you blabbing about? You call yourself a hunter?",
  " I managed to find the transcripts between Eggman and the President in the government computer.",
  " Oh, so that's why we needed the Chaos Emerald.",
  " Oh-ho! So this is the military's top-secret weapon. It's a lot smaller than I expected.",
  " I often wonder why I was created; what my purpose if for being here.",
  " Look at you, throwing a tantrum like a little kid. How totally embarrassing.",
  " I don't quite know what happened, or what went wrong. Was it a mistake to create the Ultimate Life Form?",
  " Let's go home! To the planet as cool and blue as me!",
  " Nah, I think I'm gonna give up this line of work. Too much work, for too little pay."
];

const possibleMatches = {
  shadow: shadowList,
  cop: copList,
  police: copList,
  trump: trumpList,
  president: trumpList,
  sonic: sonicList,
  sanic: sonicList, 
  emerald: emeraldList,
  shard: emeraldList,
  gem: emeraldList,
  chaos: emeraldList,
  "?": questionList
};

//Obtain a random tweet from the list
function pickTweet(){
  if (!list.length){
      list = hintList.slice();
  }
  let tweet = list.splice(Math.floor(Math.random() * list.length), 1)[0];
  sendTweet(tweet);
}

//Tweet a random tweet from hintList
function sendTweet(message){
  T.post( 'statuses/update', { status: message }, function ( err, data, response ) {
    if ( err ){
      console.log( 'error:', err );
    }
    else{
      console.log( 'tweet sent!... ' + message);
    }
  timeToTweet = 300000 - (Math.floor(Math.random() * 4) * 60000);
  console.log("next tweet is in " + timeToTweet/60000 + " minutes");
  setTimeout(pickTweet, timeToTweet);
})
}

//Generate a reply list to respond to reply
function generateReplies(text){
  var replyBank = []
  for (const match in possibleMatches){
    if (text.includes(match)){
      replyBank = [...replyBank,...possibleMatches[match]];
      console.log(match, text.includes(match));
    }
  }
  if (!replyBank.length){
    replyBank = [...defaultList];
  }
  return replyBank;  
}

//Pluck a random option from reply list
function pluckRandomMessage(replyBank){
  return replyBank.splice(Math.floor(Math.random() * replyBank.length), 1)[0];
}


//send a reply to someone who atted us
function replyTweet(tweetID, replyMSG){
  T.post('statuses/update', {in_reply_to_status_id: tweetID, status: replyMSG}, function (err, data, res) {})
  console.log('reply sent!' + replyMSG)
}

//Obtain the reply message if someone tweets at us
function tweetEvent(tweetMSG){
  if (replyCount != 0){
    replyCount++;
    console.log("no tweet sent")
    if (replyCount === 3){
      console.log(replyCount);
      replyCount = 0;
      console.log("resetting replyCount")
      return;
    }
    return;
  }
  //I'm just trusting this works
  let replyMessage = "";
  let fs = require('fs');
  let json = JSON.stringify(tweetMSG, null, 2);
  fs.writeFile("tweets.json", json, (err) =>{
    if (err) throw err;
  });

  //Obtain info from tweet that's being sent to us
  let replyTo = tweetMSG.in_reply_to_screen_name;
  let text = tweetMSG.text.toLowerCase();
  text = text.split(" ").splice(1).join(" ");

  let from = tweetMSG.user.screen_name;
  let nameID = tweetMSG.id_str;

  console.log(replyTo + from);
  console.log(text);
  console.log();

  //check if replied text contains key words we want to reply to
  let replyBank = [];
  replyBank = generateReplies(text);
  
  do {
    replyMessage = pluckRandomMessage(replyBank);

  } while (replyMessage && usedList.includes(replyMessage));
  
  if (replyMessage) {
    usedList.push(replyMessage);
  } else {
    replyBank = generateReplies(text);
    replyMessage = pluckRandomMessage(replyBank);
    usedList = [];
    usedList.push(replyMessage);
  }

  console.log(usedList);
  var reply = '@'+ from + " " + replyMessage;
  replyCount++;
  replyTweet(nameID, reply);
}

//listener for twitter replies
stream.on('tweet', tweetEvent);

//Post from hintList
setTimeout(pickTweet, timeToTweet);